[project]
name = "LSSLauncher"
version = "0.1.0"
description = ""
authors = [
    {name = "Light"}
]
readme = "README.md"
requires-python = ">3.13"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "aiohttp (>=3.12.15,<4.0.0)",
    "pyinstaller (>=6.16.0,<7.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "wmi (>=1.5.1,<2.0.0); sys.platform=='win32'",
    "pywebview (>=6.1)",
    "playsound3>=3.3.1",
]

[tool.poetry]
packages = [
    { include = "utils", from = "src" },
]

